name: Plan → Approve → Deploy (Azure Functions)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  APP_NAME: func-is-integrated-operations-api-dev-jpe-001

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: appzip
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # pytest は runner 環境にインストール
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Functions 本番用の依存は .python_packages に展開
      - name: Install function deps
        run: |
          pip install -r requirements.txt --target ./.python_packages/lib/site-packages

      # テストファイルがなかったらテストステップをスキップ
      - name: Run unit tests (optional)
        run: |
          pytest -q || TEST_EXIT=$?
          if [ -z "$TEST_EXIT" ]; then
            echo "All tests passed"
          elif [ "$TEST_EXIT" -eq 5 ]; then
            echo "No tests found, skipping..."
          else
            echo "Tests failed"
            exit $TEST_EXIT
          fi

      - name: Create deployment package
        run: |
          zip -r app.zip . -x ".git/*" ".github/*" "**/__pycache__/*" ".venv/*"

      - name: Upload artifact (Plan result)
        uses: actions/upload-artifact@v4
        with:
          name: appzip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: plan
    environment: production   # ← GitHub Environments の Required reviewers を設定
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: appzip
          path: .

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function (Production)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.APP_NAME }}
          package: app.zip

      # 簡易スモークテスト（任意）
      - name: Smoke test against Production
        run: |
          # 例: curl でエンドポイント確認
          echo "TODO: add your production smoke tests"
          exit 0
